exec function execEnv(number : int) {
	testEnv(number);
}

latent quest function testEnvAuto() {
	var i : int;
	for (i = 1; i <= 211; i += 1) {
		Sleep(4.0);
		testEnv(i);
	}
}

function testEnv(number : int) : bool {
	var envPaths    : array<string>;
	var environment : CEnvironmentDefinition;
	var envID       : int;

	envPaths.PushBack("dlc\bob\data\environment\definitions\cave\cave_catacombs.env");                                         // [1]
	envPaths.PushBack("dlc\bob\data\environment\definitions\cutscenes\cutscenes.env");                                         // [2]
	envPaths.PushBack("dlc\bob\data\environment\definitions\foggy\fog_tm.env");                                                // [3]
	envPaths.PushBack("dlc\bob\data\environment\definitions\foggy\fog_tm_pois.env");                                           // [4]
	envPaths.PushBack("dlc\bob\data\environment\definitions\quests\q702\q702_wight.env");                                      // [5]
	envPaths.PushBack("dlc\bob\data\environment\definitions\quests\q702\q702_wight_cs.env");                                   // [6]
	envPaths.PushBack("dlc\bob\data\environment\definitions\quests\q704\704_cloud.env");                                       // [7]
	envPaths.PushBack("dlc\bob\data\environment\definitions\quests\q704\704_cloud_sunny.env");                                 // [8]
	envPaths.PushBack("dlc\bob\data\environment\definitions\quests\q704\704_forrest.env");                                     // [9]
	envPaths.PushBack("dlc\bob\data\environment\definitions\quests\q704\704_forrest_cs2.env");                                 // [10]
	envPaths.PushBack("dlc\bob\data\environment\definitions\quests\q704\q704_detlaff_arena_cs.env");                           // [11]
	envPaths.PushBack("dlc\bob\data\environment\definitions\quests\q704\q704_detlaff_arena_cs_d_dies_01.env");                 // [12]
	envPaths.PushBack("dlc\bob\data\environment\definitions\quests\q704\q704_main.env");                                       // [13]
	envPaths.PushBack("dlc\bob\data\environment\definitions\quests\q704\q704_main_cs.env");                                    // [14]
	envPaths.PushBack("dlc\bob\data\environment\definitions\quests\q704\q704_snow2.env");                                      // [15]
	envPaths.PushBack("dlc\bob\data\environment\definitions\quests\q704\q704_snow2_cs.env");                                   // [16]
	envPaths.PushBack("dlc\bob\data\environment\definitions\quests\q704\fairytale\cave_catacombs_ft.env");                     // [17]
	envPaths.PushBack("dlc\bob\data\environment\definitions\quests\q704\fairytale\q704_blend.env");                            // [18]
	envPaths.PushBack("dlc\bob\data\environment\definitions\quests\q704\fairytale\q704_fairyland.env");                        // [19]
	envPaths.PushBack("dlc\bob\data\environment\definitions\quests\q704\fairytale\q704_fairyland_e_cs.env");                   // [20]
	envPaths.PushBack("dlc\bob\data\environment\definitions\quests\q704\temp\detlaff_arena_hemisphere.env");                   // [21]
	envPaths.PushBack("dlc\bob\data\environment\definitions\quests\q704\temp\q704_detlaff_arena_prod_room.env");               // [22]
	envPaths.PushBack("dlc\bob\data\environment\definitions\rainy\rain_tm.env");                                               // [23]
	envPaths.PushBack("dlc\bob\data\environment\definitions\rainy\rain_tm_pois.env");                                          // [24]
	envPaths.PushBack("dlc\bob\data\environment\definitions\sunny\dof.env");                                                   // [25]
	envPaths.PushBack("dlc\bob\data\environment\definitions\sunny\dof_interior.env");                                          // [26]
	envPaths.PushBack("dlc\bob\data\environment\definitions\sunny\sunny_bob_v4_fog_trans.env");                                // [27]
	envPaths.PushBack("dlc\bob\data\environment\definitions\sunny\sunny_bob_v7.env");                                          // [28]
	envPaths.PushBack("dlc\bob\data\environment\definitions\sunny\sunny_colors_warm.env");                                     // [29]
	envPaths.PushBack("dlc\bob\data\environment\definitions\temp\no_wind.env");                                                // [30]
	envPaths.PushBack("dlc\bob\data\fx\cutscenes\cs702_vision\vision_env.env");                                                // [31]
	envPaths.PushBack("dlc\bob\data\fx\monsters\dettlaff\monster\third_phase\detlaff_arena_hemisphere_dark_bcg.env");          // [32]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\living_world\leshy_forest.env");                       // [33]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q601\env_novigrad_sunset_cs601_09.env");               // [34]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q601\q601_ship.env");                                  // [35]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q603\env_novigrad_sunset_nn.env");                     // [36]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q603\env_novigrad_sunset_nn_blu_.env");                // [37]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_blizzard.env");                              // [38]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_blizzard_cs.env");                           // [39]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_blizzard_cs_exit_painting.env");             // [40]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_blizzard_interior.env");                     // [41]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_blizzard_interior_cs.env");                  // [42]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_creepy.env");                                // [43]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_creepy_cs.env");                             // [44]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_creepy_interior.env");                       // [45]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_dark_corridor.env");                         // [46]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_dark_corridor_creepy.env");                  // [47]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_dark_corridor_creepy_paint.env");            // [48]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_painting.env");                              // [49]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_painting_cs.env");                           // [50]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_painting_cs_closeup.env");                   // [51]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_painting_cs_midshot.env");                   // [52]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_painting_cs_wideshot.env");                  // [53]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_painting_interior.env");                     // [54]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_painting_interior_cs.env");                  // [55]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_unmasking.env");                             // [56]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_unmasking_dark.env");                        // [57]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q604\q604_unmasking_shadow_more_details.env");         // [58]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q605\q605_hell_red_blockout.env");                     // [59]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q605\q605_hell_red_blockout_last_arena.env");          // [60]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q605\q605_hell_red_blockout_mansion.env");             // [61]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\in_progress\q605\q605_hell_temple_blockout.env");                  // [62]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\trailer\bury_iris_side.env");                                      // [63]
	envPaths.PushBack("dlc\ep1\data\environment\definitions\trailer\enter_painting_wide.env");                                 // [64]
	envPaths.PushBack("dlc\ep1\data\quests\quest_files\q603_bank\env_novigrad_sunset_usm.env");                                // [65]
	envPaths.PushBack("dlc\ep1\data\quests\quest_files\q603_bank\env_novigrad_sunset_usm_7.env");                              // [66]
	envPaths.PushBack("dlc\ep1\data\quests\quest_files\q603_bank\env_novigrad_sunset_usm_8.env");                              // [67]
	envPaths.PushBack("dlc\ep1\data\quests\quest_files\q603_bank\testing\env_novigrad_sunset_usm_2.env");                      // [68]
	envPaths.PushBack("dlc\ep1\data\quests\quest_files\q603_bank\testing\env_novigrad_sunset_usm_4.env");                      // [69]
	envPaths.PushBack("dlc\ep1\data\quests\quest_files\q603_bank\testing\env_novigrad_sunset_usm_5.env");                      // [70]
	envPaths.PushBack("dlc\ep1\data\quests\quest_files\q603_bank\testing\env_novigrad_sunset_usm_6.env");                      // [71]
	envPaths.PushBack("dlc\ep1\data\quests\quest_files\q603_bank\testing\env_novigrad_sunset_usm_8.env");                      // [72]
	envPaths.PushBack("dlc\ep1\environment\definitions\q601\env_novigrad_cave_frogarena.env");                                 // [73]
	envPaths.PushBack("dlc\ep1\environment\definitions\q601\q601_dark_clouds_heavy_rain.env");                                 // [74]
	envPaths.PushBack("dlc\ep1\environment\definitions\q601\q601_dark_clouds_heavy_rain_scene.env");                           // [75]
	envPaths.PushBack("dlc\ep1\environment\definitions\q602\q602_wedding_overlay.env");                                        // [76]
	envPaths.PushBack("dlc\ep1\environment\definitions\q602\q602_wedding_overlay_2.env");                                      // [77]
	envPaths.PushBack("dlc\ep1\environment\definitions\q605\env_novigrad_sunset_q605_temple_meeting_02.env");                  // [78]
	envPaths.PushBack("dlc\ep1\environment\definitions\q605\q605_no_wind.env");                                                // [79]
	envPaths.PushBack("environment\definitions\cutscenes_definition\cutscen_definition_global.env");                           // [80]
	envPaths.PushBack("environment\definitions\cutscenes_definition\cutscen_definition_kaer_morhen.env");                      // [81]
	envPaths.PushBack("environment\definitions\cutscenes_definition\envs_for_cutscenes\dandelion_cellar_cutscene.env");        // [82]
	envPaths.PushBack("environment\definitions\cutscenes_definition\envs_for_cutscenes\q106_temp_island_env_int_cs.env");      // [83]
	envPaths.PushBack("environment\definitions\cutscenes_definition\envs_for_cutscenes\q__cs_ship_leaves_1.env");              // [84]
	envPaths.PushBack("environment\definitions\env_island_of_mist\env_island_fog_1.env");                                      // [85]
	envPaths.PushBack("environment\definitions\env_island_of_mist\env_island_of_mist.env");                                    // [86]
	envPaths.PushBack("environment\definitions\env_island_of_mist\env_island_of_mist_2.env");                                  // [87]
	envPaths.PushBack("environment\definitions\env_island_of_mist\env_island_of_mist_dark.env");                               // [88]
	envPaths.PushBack("environment\definitions\env_island_of_mist\env_island_of_mist_dark_cutscen.env");                       // [89]
	envPaths.PushBack("environment\definitions\env_nomansland\env_nml_global_dark_sunset.env");                                // [90]
	envPaths.PushBack("environment\definitions\env_nomansland\env_nml_global_dark_sunset_interior.env");                       // [91]
	envPaths.PushBack("environment\definitions\env_nomansland\barons_lair\env_nml_barons_castle_v2.env");                      // [92]
	envPaths.PushBack("environment\definitions\env_nomansland\crossroads_inn\env_nml_crossroads_inn_v2.env");                  // [93]
	envPaths.PushBack("environment\definitions\env_nomansland\keira_swcret_room\env_keira_secret_2.env");                      // [94]
	envPaths.PushBack("environment\definitions\env_nomansland\nml_global\env_nml_swamps_v1.env");                              // [95]
	envPaths.PushBack("environment\definitions\env_nomansland\nml_global\env_nml_swamps_v1_a_ps4_flat24.env");                 // [96]
	envPaths.PushBack("environment\definitions\env_nomansland\salt_mines\wip\env_salt_mine_filmic_01.env");                    // [97]
	envPaths.PushBack("environment\definitions\env_novigrad\env_interior.env");                                                // [98]
	envPaths.PushBack("environment\definitions\env_novigrad\env_novigrad_cave.env");                                           // [99]
	envPaths.PushBack("environment\definitions\env_novigrad\env_novigrad_cave_blizzard.env");                                  // [100]
	envPaths.PushBack("environment\definitions\env_novigrad\env_novigrad_cave_dark.env");                                      // [101]
	envPaths.PushBack("environment\definitions\env_novigrad\env_novigrad_cave_red_water.env");                                 // [102]
	envPaths.PushBack("environment\definitions\env_novigrad\env_novigrad_cave_simpa.env");                                     // [103]
	envPaths.PushBack("environment\definitions\env_novigrad\env_novigrad_dark_clouds.env");                                    // [104]
	envPaths.PushBack("environment\definitions\env_novigrad\env_novigrad_dark_clouds_heavy.env");                              // [105]
	envPaths.PushBack("environment\definitions\env_novigrad\env_novigrad_dark_clouds_heavy_rain_color.env");                   // [106]
	envPaths.PushBack("environment\definitions\env_novigrad\env_novigrad_int.env");                                            // [107]
	envPaths.PushBack("environment\definitions\env_novigrad\env_novigrad_q602_sex_empty_1.env");                               // [108]
	envPaths.PushBack("environment\definitions\env_novigrad\env_novigrad_storm.env");                                          // [109]
	envPaths.PushBack("environment\definitions\env_novigrad\env_novigrad_sunset.env");                                         // [110]
	envPaths.PushBack("environment\definitions\env_novigrad\env_novigrad_sunset_q602_dog.env");                                // [111]
	envPaths.PushBack("environment\definitions\env_novigrad\env_novigrad_sunset_q602_sex.env");                                // [112]
	envPaths.PushBack("environment\definitions\env_novigrad\env_novigrad_sunset_q603_heist_starts.env");                       // [113]
	envPaths.PushBack("environment\definitions\env_novigrad\elven_king_dandelion\env_elven_king_dandelion_copy.env");          // [114]
	envPaths.PushBack("environment\definitions\env_novigrad\env_novigrad_global\env_novigrad_city.env");                       // [115]
	envPaths.PushBack("environment\definitions\env_novigrad\env_novigrad_global\raw_novigrad\env_novigrad_0_storm_1.env");     // [116]
	envPaths.PushBack("environment\definitions\env_novigrad\env_novigrad_global\raw_novigrad\underwater.env");                 // [117]
	envPaths.PushBack("environment\definitions\env_novigrad\interiors\dandelion\env_dandelion.env");                           // [118]
	envPaths.PushBack("environment\definitions\env_novigrad\interiors\dandelion\wip\env_interior_1.env");                      // [119]
	envPaths.PushBack("environment\definitions\env_novigrad\interiors\dandelion\wip\env_interior_2.env");                      // [120]
	envPaths.PushBack("environment\definitions\env_novigrad\novigrad_sewers\env_novigrad_sewers_filmic_v1.env");               // [121]
	envPaths.PushBack("environment\definitions\env_prologue\env_prolog_colors_cinematic_tonemapping.env");                     // [122]
	envPaths.PushBack("environment\definitions\env_prologue\env_prolog_colors_v1_b_sunset.env");                               // [123]
	envPaths.PushBack("environment\definitions\env_prologue\env_prolog_global\env_prolog_global_raw_v2_a_interior.env");       // [124]
	envPaths.PushBack("environment\definitions\env_skellige\env_fight_island_arena_.env");                                     // [125]
	envPaths.PushBack("environment\definitions\env_skellige\env_fight_ship.env");                                              // [126]
	envPaths.PushBack("environment\definitions\env_skellige\env_pbr_skellige_len_temp.env");                                   // [127]
	envPaths.PushBack("environment\definitions\env_skellige\env_pbr_skellige_v7_tm_fog_sky_b_tm_exp.env");                     // [128]
	envPaths.PushBack("environment\definitions\env_skellige\env_skellige_brown.env");                                          // [129]
	envPaths.PushBack("environment\definitions\env_skellige\env_skellige_brown_dark_clouds.env");                              // [130]
	envPaths.PushBack("environment\definitions\env_skellige\env_skellige_dark_clouds.env");                                    // [131]
	envPaths.PushBack("environment\definitions\env_skellige\env_skellige_rain_storm.env");                                     // [132]
	envPaths.PushBack("environment\definitions\env_skellige\env_skellige_rain_storm_arena.env");                               // [133]
	envPaths.PushBack("environment\definitions\env_skellige\env_winter_skellige.env");                                         // [134]
	envPaths.PushBack("environment\definitions\env_skellige\cataclysm\env_skellige_cataclysm_1.env");                          // [135]
	envPaths.PushBack("environment\definitions\env_skellige\exteriors\env_skellige_leshy_forest_v3.env");                      // [136]
	envPaths.PushBack("environment\definitions\env_skellige\herbarium\env_herbarium_fall_2.env");                              // [137]
	envPaths.PushBack("environment\definitions\env_skellige\herbarium\wip\env_herbarium_mordor_1.env");                        // [138]
	envPaths.PushBack("environment\definitions\env_skellige\interiors\kt_castle\env_kaer_trolde_interior_1.env");              // [139]
	envPaths.PushBack("environment\definitions\env_skellige\interiors\kt_castle\env_kaer_trolde_interior_2.env");              // [140]
	envPaths.PushBack("environment\definitions\env_skellige\q203_him\env_skellige_udalryk.env");                               // [141]
	envPaths.PushBack("environment\definitions\env_skellige\q205\env_bathouse_v01.env");                                       // [142]
	envPaths.PushBack("environment\definitions\env_skellige\q210\env_skellige_q210.env");                                      // [143]
	envPaths.PushBack("environment\definitions\env_skellige\q501\q501_underwater.env");                                        // [144]
	envPaths.PushBack("environment\definitions\env_skellige\q502\cutscen_definition_global_q502_wyzima.env");                  // [145]
	envPaths.PushBack("environment\definitions\env_skellige\q502\cutscen_definition_global_q502_wyzima_v2.env");               // [146]
	envPaths.PushBack("environment\definitions\env_skellige\q502\cutscen_definition_global_q502_wyzima_v3.env");               // [147]
	envPaths.PushBack("environment\definitions\env_skellige\q502\cutscen_definition_global_q502_wyzima_v4.env");               // [148]
	envPaths.PushBack("environment\definitions\env_skellige\q502\env_kaer_morhen_v09_tm_q502_cold_light.env");                 // [149]
	envPaths.PushBack("environment\definitions\env_skellige\q502\env_skellige_brown_q502_by_light.env");                       // [150]
	envPaths.PushBack("environment\definitions\env_skellige\q502\env_skellige_brown_q502_by_light_2.env");                     // [151]
	envPaths.PushBack("environment\definitions\env_skellige\q502\env_skellige_brown_q502_by_light_3.env");                     // [152]
	envPaths.PushBack("environment\definitions\env_skellige\q502\env_skellige_brown_q502_by_light_4.env");                     // [153]
	envPaths.PushBack("environment\definitions\env_skellige\q502\env_skellige_brown_q502_end.env");                            // [154]
	envPaths.PushBack("environment\definitions\env_skellige\shore_cave_sq209\env_skellige_sq209_02.env");                      // [155]
	envPaths.PushBack("environment\definitions\env_skellige\shore_cave_sq209\env_skellige_sq209_03.env");                      // [156]
	envPaths.PushBack("environment\definitions\env_spiral\env_desert_clear.env");                                              // [157]
	envPaths.PushBack("environment\definitions\env_spiral\env_elven_city_4_11.env");                                           // [158]
	envPaths.PushBack("environment\definitions\env_spiral\env_spiral_dark_valley.env");                                        // [159]
	envPaths.PushBack("environment\definitions\env_spiral\env_spiral_snow_hour_6_22.env");                                     // [160]
	envPaths.PushBack("environment\definitions\env_spiral\env_spiral_snow_hour_6_22_cave.env");                                // [161]
	envPaths.PushBack("environment\definitions\env_winter\env_winter_epilog.env");                                             // [162]
	envPaths.PushBack("environment\definitions\env_winter\env_winter_epilog_white_grass.env");                                 // [163]
	envPaths.PushBack("environment\definitions\env_winter\env_winter_epilog_white_grass_hendriks_basement.env");               // [164]
	envPaths.PushBack("environment\definitions\env_winter\env_winter_epilog_white_grass_hendriks_house.env");                  // [165]
	envPaths.PushBack("environment\definitions\env_winter\env_winter_v0_white_thaw.env");                                      // [166]
	envPaths.PushBack("environment\definitions\gui_character_display\gui_character_environment.env");                          // [167]
	envPaths.PushBack("environment\definitions\kaer_morhen\interior\env_kaer_morhen_hdr_int.env");                             // [168]
	envPaths.PushBack("environment\definitions\kaer_morhen\kaer_morhen_battle\wip\env_km_dark_clouds_heavy_rain_color.env");   // [169]
	envPaths.PushBack("environment\definitions\kaer_morhen\kaer_morhen_battle\wip\kaer_morhen_battle.env");                    // [170]
	envPaths.PushBack("environment\definitions\kaer_morhen\kaer_morhen_battle\wip\kaer_morhen_battle_preview_01.env");         // [171]
	envPaths.PushBack("environment\definitions\kaer_morhen\kaer_morhen_global\env_kaer_morhen_v09_hdr_int.env");               // [172]
	envPaths.PushBack("environment\definitions\kaer_morhen\kaer_morhen_global\env_kaer_morhen_v09_tm.env");                    // [173]
	envPaths.PushBack("environment\definitions\kaer_morhen\kaer_morhen_global\env_kaer_morhen_v09_usm_sex_scene.env");         // [174]
	envPaths.PushBack("environment\definitions\kaer_morhen\kaer_morhen_global\env_kaer_morhen_v09_usm_sex_scene_v3.env");      // [175]
	envPaths.PushBack("environment\definitions\kaer_morhen\kaer_morhen_global\env_kaer_morhen_vesemir_v0_hour_3_30.env");      // [176]
	envPaths.PushBack("environment\definitions\kaer_morhen\kaer_morhen_global\q401\env_kaer_morhen_v09_q401.env");             // [177]
	envPaths.PushBack("environment\definitions\novigrad\env_global_clear_interior.env");                                       // [178]
	envPaths.PushBack("environment\definitions\skellige\env_abandoned_mine.env");                                              // [179]
	envPaths.PushBack("environment\definitions\skellige\env_bies_hypnotize.env");                                              // [180]
	envPaths.PushBack("environment\definitions\skellige\env_dense_fog_mq2041.env");                                            // [181]
	envPaths.PushBack("environment\definitions\usm\battle_02.env");                                                            // [182]
	envPaths.PushBack("environment\definitions\usm\battle_02_copy.env");                                                       // [183]
	envPaths.PushBack("environment\definitions\usm\battle_02_copy_nofx.env");                                                  // [184]
	envPaths.PushBack("environment\definitions\usm\battle_02_no blue_lights.env");                                             // [185]
	envPaths.PushBack("environment\definitions\usm\battle_02_no _sun.env");                                                    // [186]
	envPaths.PushBack("environment\definitions\usm\battle_02_shadow_light.env");                                               // [187]
	envPaths.PushBack("environment\definitions\usm\cs002_wild_hunt_chase_p4.env");                                             // [188]
	envPaths.PushBack("environment\definitions\usm\cs301_dream_ciri_and_jasker_p2.env");                                       // [189]
	envPaths.PushBack("environment\definitions\usm\cs501_ciri_escape.env");                                                    // [190]
	envPaths.PushBack("environment\definitions\usm\cs501_naglfar_arrives.env");                                                // [191]
	envPaths.PushBack("environment\definitions\usm\cs__departure_2.env");                                                      // [192]
	envPaths.PushBack("environment\definitions\usm\naglfar_freezes_p2.env");                                                   // [193]
	envPaths.PushBack("environment\definitions\usm\naglfar_freezes_p2_face.env");                                              // [194]
	envPaths.PushBack("environment\definitions\wyzima\global\env_wyzima.env");                                                 // [195]
	envPaths.PushBack("environment\definitions\wyzima\global\env_wyzima_interior.env");                                        // [196]
	envPaths.PushBack("fx\demos_and_temp_fx\darkness_upon_us.env");                                                            // [197]
	envPaths.PushBack("fx\gameplay\mutation\mutation_10\euphoria_env.env");                                                    // [198]
	envPaths.PushBack("fx\gameplay\mutation\mutation_7\mtn_7_adrenaline_burst_env.env");                                       // [199]
	envPaths.PushBack("fx\gameplay\mutation\mutation_7\mtn_7_adrenaline_drop_env.env");                                        // [200]
	envPaths.PushBack("fx\quest\q103\q103_castle_fire_noshafts.env");                                                          // [201]
	envPaths.PushBack("fx\quest\q103\q103_env_barons_burial.env");                                                             // [202]
	envPaths.PushBack("fx\quest\q107\q107_env_witch_village_fog.env");                                                         // [203]
	envPaths.PushBack("quests\part_2\quest_files\q106_tower\entities\env_mist_q106.env");                                      // [204]
	envPaths.PushBack("quests\part_2\quest_files\q106_tower\entities\q106_temp_island_env.env");                               // [205]
	envPaths.PushBack("quests\part_2\quest_files\q106_tower\entities\q106_temp_island_env_int.env");                           // [206]
	envPaths.PushBack("environment\definitions\dashdot_env_nvg_global_23_07_2013_copy.env");                                   // [207]
	
	// bugged ?
	envPaths.PushBack("engine\environments\full_color.env");                                                                   // [208]
	envPaths.PushBack("engine\environments\full_dark.env");                                                                    // [209]
	envPaths.PushBack("engine\environments\std_raw.env");                                                                      // [210]
	envPaths.PushBack("engine\thumbnails\thumbnail_env.env");                                                                  // [211] 

	if (FactsDoesExist("test_env_id") && FactsQuerySum("test_env_id") > 0) {
		envID = FactsQuerySum("test_env_id");
		DeactivateEnvironment(envID, 0.1f);
		FactsSet("test_env_id", 0);
	}

	if (number < 1 || number > envPaths.Size()) {
		theGame.GetGuiManager().ShowNotification("Number must be in range [1 - " + envPaths.Size() + "] !");
		return false;
	}

	theGame.GetGuiManager().ShowNotification("Applying env [" + number + "]: " + envPaths[number - 1]);
	LogChannel('TestEnv', "Applying env [" + number + "]: " + envPaths[number - 1]);
	environment = (CEnvironmentDefinition)LoadResource(envPaths[number - 1], true);
    envID = ActivateEnvironmentDefinition( environment, 1000, 1, 0.5f );
    theGame.SetEnvironmentID(envID);
    FactsAdd("test_env_id", envID);

    return true;
}